### ISSUE TITLE
GetChallangeFeed Not Working

### ISSUE THREAD

**Issue by kticoder** [demon071/Tiktok-API-Python#15]
```

from TiktokApi import *

Api = Tiktok()

limit = 40
count = 0
setFlag = 0
max_cursor = 0
while True:
    Feed, cookie = Api.getChallengeFeed(challenge='funny', max_cursor=max_cursor)
    dl = Download(cookie=cookie, path='video')
    for post in Feed['itemListData']:
        video_url = post['itemInfos']['video']['urls'][0]
        video_id = post['itemInfos']['id']
        print(video_id)
        # download video
        dl.downloadVideo(url=video_url, file_name=video_id)
        print('Download video {}.mp4'.format(video_id))
        count += 1
        if count == limit:
            setFlag = 1
            break
    max_cursor += 30 
    if setFlag == 1:
        break
```

Error:
```

  File "/home/kadirilgin1453/Python-Projeleri/TiktokProject/TiktokApi/api.py", line 213, in getInfoChallenge
    resp = self.__extra_next_data__(res.text)
  File "/home/kadirilgin1453/Python-Projeleri/TiktokProject/TiktokApi/api.py", line 264, in __extra_next_data__
    res = re.search('<script id="sigi-persisted-data">(.*)</script><script', html).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Traceback (most recent call last):
  File "/home/kadirilgin1453/Python-Projeleri/TiktokProject/main.py", line 11, in <module>
    Feed, cookie = Api.getChallengeFeed(challenge='funny', max_cursor=max_cursor)
TypeError: cannot unpack non-iterable bool object
```

- [+] Python 3.10.1

**Comment by demon071** [comment]
Hello, I fixed the error
