### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group' / TypeError: cannot unpack non-iterable bool object

### ISSUE THREAD

**Issue by 1232154pp4749687** [demon071/Tiktok-API-Python#18]
Hello,
While trying getUserFeed.py I get these errors:

```
Traceback (most recent call last):
  File "F:\Escritorio\Tiktok-API-Python-master\TiktokApi\api.py", line 198, in getInfoUser
    resp = self.extra_next_data(res.text)
  File "F:\Escritorio\Tiktok-API-Python-master\TiktokApi\api.py", line 270, in extra_next_data
    res = re.search('script id=\"SIGI_STATE\" type=\"application/json\">(.*)</script><script id=\"SIGI_RETRY\"', html).group(0)
```
**AttributeError: 'NoneType' object has no attribute 'group'** ^^

```
Traceback (most recent call last):
  File "F:\Escritorio\Tiktok-API-Python-master\getUserFeed.py", line 26, in <module>
    userFeed, cookie = Api.getUserFeed(username, max_cursor=max_cursor)
```
**TypeError: cannot unpack non-iterable bool object** ^^

Hope you guys can help me :)

**Comment by demon071** [comment]
> 

i tested, the api still works, with your error please check the IP or try with another IP, when verified captcha can't get the data
