### ISSUE TITLE
selenium.common.exceptions.TimeoutException: Message: script timeout

### ISSUE THREAD

**Issue by hosam7080** [demon071/Tiktok-API-Python#31]
I'm getting this error 
`Traceback (most recent call last):
  File "C:\Users\hosam\Desktop\workspace1\ocean_project\Tiktok-API-Python\TiktokApi\api.py", line 57, in getUserFeed
    data = self.browser.fetch_browser(api_url, tt_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hosam\Desktop\workspace1\ocean_project\Tiktok-API-Python\TiktokApi\browser.py", line 65, in fetch_browser
    return self.driver.execute_async_script(js)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hosam\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 526, in execute_async_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hosam\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\hosam\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: script timeout
  (Session info: chrome=107.0.5304.107)
Stacktrace:
Backtrace:
        Ordinal0 [0x00F3ACD3+2075859]
        Ordinal0 [0x00ECEE61+1633889]
        Ordinal0 [0x00DCB680+571008]
        Ordinal0 [0x00E2C20A+967178]
        Ordinal0 [0x00E1731C+881436]
        Ordinal0 [0x00E2B56A+963946]
        Ordinal0 [0x00E17136+880950]
        Ordinal0 [0x00DEFEFD+720637]
        Ordinal0 [0x00DF0F3F+724799]
        GetHandleVerifier [0x011EEED2+2769538]
        GetHandleVerifier [0x011E0D95+2711877]
        GetHandleVerifier [0x00FCA03A+521194]
        GetHandleVerifier [0x00FC8DA0+516432]
        Ordinal0 [0x00ED682C+1665068]
        Ordinal0 [0x00EDB128+1683752]
        Ordinal0 [0x00EDB215+1683989]
        Ordinal0 [0x00EE6484+1729668]
        BaseThreadInitThunk [0x76C7FEF9+25]
        RtlGetAppContainerNamedObjectPath [0x77577BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77577B8E+238]
`
when running getUserFeed.py

**Comment by demon071** [comment]
```python
Api.openBrowser(url, True)
import time
time.sleep(60)
```
you need to skip the captcha to be able to authenticate the browser, put a sleep time after the browser opens, and ignore the capthca
